version: '3'

services:
  server:
    build: ./server
    env_file:
      ./server/.env
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data

  parser:
    build: ./parser
    env_file:
      ./parser/.env
    volumes:
      - ./data:/app/data
